// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQcdY3x5YZrhkC0uv8VX5tNXSrfva1gLg',
    appId: '1:131913164620:web:0198d114f76f3c0b4b11e9',
    messagingSenderId: '131913164620',
    projectId: 'e-waste-d44a8',
    authDomain: 'e-waste-d44a8.firebaseapp.com',
    storageBucket: 'e-waste-d44a8.firebasestorage.app',
    measurementId: 'G-PZ55CQGBYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLY6XLifEJovvUjqthRrhtryJKFVLs2gQ',
    appId: '1:131913164620:android:b4318f4597e7788b4b11e9',
    messagingSenderId: '131913164620',
    projectId: 'e-waste-d44a8',
    storageBucket: 'e-waste-d44a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLYRgNbseTdfa2eYMEOQmfW53XKC3wBAI',
    appId: '1:131913164620:ios:4d365560d4485ab54b11e9',
    messagingSenderId: '131913164620',
    projectId: 'e-waste-d44a8',
    storageBucket: 'e-waste-d44a8.firebasestorage.app',
    iosClientId: '131913164620-1f77jk5nnk0tjkg2iurcf3c63ob1k6k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eWaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLYRgNbseTdfa2eYMEOQmfW53XKC3wBAI',
    appId: '1:131913164620:ios:4d365560d4485ab54b11e9',
    messagingSenderId: '131913164620',
    projectId: 'e-waste-d44a8',
    storageBucket: 'e-waste-d44a8.firebasestorage.app',
    iosClientId: '131913164620-1f77jk5nnk0tjkg2iurcf3c63ob1k6k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eWaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQcdY3x5YZrhkC0uv8VX5tNXSrfva1gLg',
    appId: '1:131913164620:web:34d786d26c40b2b44b11e9',
    messagingSenderId: '131913164620',
    projectId: 'e-waste-d44a8',
    authDomain: 'e-waste-d44a8.firebaseapp.com',
    storageBucket: 'e-waste-d44a8.firebasestorage.app',
    measurementId: 'G-DGE36ZSDZD',
  );

}